### 1. Obtener lista de materias
GET http://localhost:3002/api/subjects

###

### 2. Obtener todas las calificaciones (Inicialmente vacío)
GET http://localhost:3002/api/grades

###

### 3. Crear una calificación válida
POST http://localhost:3002/api/grades
Content-Type: application/json

{
  "student_name": "Leonel Oro Valor",
  "subject_id": 1,
  "note1": 8.50,
  "note2": 9.00,
  "note3": 10.00
}

###

### 4. Intentar crear duplicado (Mismo alumno y misma materia)
POST http://localhost:3002/api/grades
Content-Type: application/json

{
  "student_name": "Leonel Oro Valor",
  "subject_id": 1,
  "note1": 7.00,
  "note2": 7.00,
  "note3": 7.00
}

###

### 5. Intentar crear calificación con nota fuera de rango (ejemplo: nota 12)
POST http://localhost:3002/api/grades
Content-Type: application/json

{
  "student_name": "Martín Pérez",
  "subject_id": 2,
  "note1": 12.00,
  "note2": 8.00,
  "note3": 9.00
}

###

### 6. Obtener calificación por ID
GET http://localhost:3002/api/grades/1

###

### 7. Actualizar notas de un alumno
PUT http://localhost:3002/api/grades/1
Content-Type: application/json

{
  "note1": 10.00
}

###

### 8. Eliminar registro por ID
DELETE http://localhost:3002/api/grades/1