CREATE DATABASE IF NOT EXISTS tp2_ejercicio1;
USE tp2_ejercicio1;

CREATE TABLE IF NOT EXISTS rectangles (
    id INT AUTO_INCREMENT PRIMARY KEY,
    base DECIMAL(10,2) NOT NULL,
    height DECIMAL(10,2) NOT NULL,
    perimeter DECIMAL(10,2) NOT NULL,
    surface DECIMAL(10,2) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);